Transform: AWS::Serverless-2016-10-31

Resources:

  BankSnsPawnShop:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      PackageType: Zip
      Runtime: nodejs12.x
      CodeUri: src
      Handler: BankSns.handler
      FunctionName: 'BankSns3PawnShop'
      Description: 'Pawn Shop'
      Events:
        MortgageQuoteRequest:
          Type: SNS
          Properties:
            Topic: !Ref QuoteRequestChannel
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt FilterMortgageQuotesBus.Arn
      Environment:
        Variables:
          BANK_ID: PawnShop
          BASE_RATE: 5
          MAX_LOAN_AMOUNT: 500000
          MIN_CREDIT_SCORE: 400

  BankSnsUniversal:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      PackageType: Zip
      Runtime: nodejs12.x
      CodeUri: src
      Handler: BankSns.handler
      FunctionName: 'BankSns3Universal'
      Description: 'Universal Bank'
      Events:
        MortgageQuoteRequest:
          Type: SNS
          Properties:
            Topic: !Ref QuoteRequestChannel
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt FilterMortgageQuotesBus.Arn
      Environment:
        Variables:
          BANK_ID: Universal
          BASE_RATE: 4
          MAX_LOAN_AMOUNT: 700000
          MIN_CREDIT_SCORE: 500

  BankSnsPremium:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      PackageType: Zip
      Runtime: nodejs12.x
      CodeUri: src
      Handler: BankSns.handler
      FunctionName: 'BankSns3Premium'
      Description: 'Premium Bank'
      Events:
        MortgageQuoteRequest:
          Type: SNS
          Properties:
            Topic: !Ref QuoteRequestChannel
      EventInvokeConfig:
        DestinationConfig:
          OnSuccess:
            Type: EventBridge
            Destination: !GetAtt FilterMortgageQuotesBus.Arn
      Environment:
        Variables:
          BANK_ID: Premium
          BASE_RATE: 3
          MAX_LOAN_AMOUNT: 900000
          MIN_CREDIT_SCORE: 600

# Create Quote Request Channel

  QuoteRequestChannel:
    Type: AWS::SNS::Topic
    DeletionPolicy: Delete
    Properties:
      TopicName: MortgageQuoteRequest3

# Create Mortgage Response Channel and Link to Banks via Destination and EventBridge

  QuoteResponseChannel:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    Properties:
      QueueName: MortgageQuotes3
      MessageRetentionPeriod: 300

  FilterMortgageQuotesBus:
    Type: AWS::Events::EventBus
    DeletionPolicy: Delete
    Properties:
      Name: LoanBroker3

  RouteMortgageQuotes:
    Type: AWS::Events::Rule
    DeletionPolicy: Retain
    Properties:
      Name: RouteMortgageQuotes3
      Description: "Filter out empty quotes"
      EventBusName: !GetAtt FilterMortgageQuotesBus.Name
      EventPattern:
        detail:
          requestContext:
            functionArn: [{ prefix: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:BankSns3' }]
          responsePayload:
            bankId: [{ exists: true }]
      Targets:
        - Arn: !GetAtt QuoteResponseChannel.Arn
          InputPath: $.detail.responsePayload
          Id: MortgageQuotes

  AllowMessagesToResponseChannel:    
    Type: AWS::SQS::QueuePolicy
    DeletionPolicy: Delete
    Properties:
      Queues:
        - !Ref QuoteResponseChannel
      PolicyDocument:
        Statement:
          - Action:
              - "SQS:SendMessage"
            Effect: "Allow"
            Resource: !GetAtt QuoteResponseChannel.Arn
            Principal:
              Service: events.amazonaws.com

